"""Unit tests for sysadmin.pipeline (Arc-Orc-Rev Pipeline Runner)."""

import json
import pytest

from mcp_core.context_store import ContextStore
from pipeline import (
    SMMP_PROFILES,
    PipelineState,
    parse_llm_json,
    load_role_prompt,
    run_pipeline,
    resume_pipeline,
)


def test_smmp_profiles():
    required_roles = ["architect", "orchestrator", "reviewer", "security", "coder", "sysadmin"]
    for role in required_roles:
        assert role in SMMP_PROFILES
        assert "temperature" in SMMP_PROFILES[role]
        assert "top_p" in SMMP_PROFILES[role]


def test_parse_llm_json():
    # 1. Plain JSON
    raw = '{"key": "value"}'
    assert parse_llm_json(raw) == {"key": "value"}

    # 2. Markdown fenced JSON
    fenced = "Here is your plan:\n```json\n{\n  \"action\": \"test\"\n}\n```"
    assert parse_llm_json(fenced) == {"action": "test"}

    # 3. JSON with Ollama telemetry footer
    with_telemetry = (
        '{"status": "ok"}\n\n---\n*Generated by `qwen2.5-coder:7b`: 50 tokens in 0.5s*'
    )
    assert parse_llm_json(with_telemetry) == {"status": "ok"}


def test_pipeline_state_serde():
    state = PipelineState("run-xyz", "Test prompt")
    state.add_event("test_event", "Detail message", "1")
    state.tasks["t-001"] = {"status": "pending", "retries": 0, "role": "coder"}

    d = state.to_dict()
    assert d["run_id"] == "run-xyz"
    assert d["status"] == "running"
    assert len(d["events"]) == 1

    restored = PipelineState.from_dict(d)
    assert restored.run_id == state.run_id
    assert restored.original_prompt == state.original_prompt
    assert restored.tasks == state.tasks


def test_load_role_prompt():
    prompt = load_role_prompt("architect")
    assert "Architect" in prompt
    assert "PlanMessage" in prompt


def test_run_pipeline_mocked_success(tmp_path, monkeypatch):
    runs_dir = tmp_path / "runs"
    store = ContextStore(runs_dir=str(runs_dir))

    prompt = "Deploy a defensive backup script"
    run_id = "test-run-mock-001"

    # Mock stage_chat responses
    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        if role == "architect":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "Write backup script",
                        "domain_tags": ["Defensive Bash Scripting"],
                        "tools_required": ["run_bash"],
                    }
                ],
                "cognition": {
                    "analysis": "Root cause analysis for backup deployment.",
                    "risks": "Potential permission denied on target volume.",
                    "solution": "Generate defensive script with explicit validation.",
                    "verification": "Verify exit code 0 and destination archive existence.",
                },
            })
        elif role == "orchestrator":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "annotated_plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "dag": {
                    "nodes": ["t-001"],
                    "edges": [],
                },
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "Write backup script",
                        "domain_tags": ["Defensive Bash Scripting"],
                        "assigned_agent": "coder",
                        "tools_required": ["run_bash"],
                        "inputs": [],
                        "outputs": ["backup.sh"],
                        "constraints": [],
                    }
                ],
                "cognition": {
                    "analysis": "Pillar 1 analysis of DAG structure and task assignments.",
                    "risks": "Pillar 2 risks of tool execution and concurrency.",
                    "solution": "Pillar 3 deterministic scheduling for single-task DAG.",
                    "verification": "Pillar 4 validation of DAG acyclicity and tool registry bindings.",
                },
            })
        elif role == "reviewer":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "return_to": None,
                "violations": [],
                "cognition": {
                    "analysis": "Plan meets all architectural and safety requirements.",
                    "risks": "No blocking risks identified during audit.",
                    "solution": "Approve plan for STRIDE threat modeling.",
                    "verification": "Confirmed prompt fidelity and schema compliance.",
                },
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "fault_type": None,
                "threats": [],
                "cognition": {
                    "analysis": "STRIDE evaluation performed across all categories.",
                    "risks": "No unmitigated threats detected.",
                    "solution": "Clear plan for dispatch.",
                    "verification": "Verified sandbox constraints and tool boundaries.",
                },
            })
        elif role == "coder":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "execution_result",
                "run_id": run_id,
                "task_id": "t-001",
                "role": "coder",
                "status": "success",
                "outputs": {
                    "backup.sh": (
                        "#!/usr/bin/env bash\n"
                        "set -euo pipefail\n"
                        "trap 'echo \"error\" >&2; exit 1' ERR\n"
                        "echo \"backup complete\"\n"
                        "exit 0\n"
                    )
                },
                "cognition": {
                    "analysis": "Coder analysis of implementation.",
                    "risks": "No execution risks encountered.",
                    "solution": "Authored defensive script.",
                    "verification": "Syntax verified.",
                },
            })
        raise ValueError(f"Unexpected role: {role}")

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)
    monkeypatch.setattr("pipeline.handle_execute_task", lambda *a, **kw: "- **Exit Code**: `0`\nSuccess")
    monkeypatch.setattr("pipeline.handle_write_file", lambda *a, **kw: "Wrote file")

    final_state = run_pipeline(prompt=prompt, run_id=run_id, store=store)

    assert final_state["status"] == "complete"
    assert final_state["current_phase"] == "complete"
    assert "t-001" in final_state["tasks"]

    # Verify run was sealed to cold storage
    archive_path = store._archive_path(run_id)
    assert (tmp_path / "runs" / f"{run_id}.tar.zst").exists()

    # Verify we can load back state from sealed archive
    loaded_state = store.load(f"runs/{run_id}/state.json")
    assert loaded_state["status"] == "complete"


def test_run_pipeline_pre_filter_rejection_routes_to_orchestrator(tmp_path, monkeypatch):
    runs_dir = tmp_path / "runs"
    store = ContextStore(runs_dir=str(runs_dir))

    prompt = "Test pre-filter routing"
    run_id = "test-run-mock-002"
    reviewer_called = []
    orchestrator_call_count = [0]

    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        if role == "architect":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "tasks": [{"task_id": "t-001", "description": "task", "domain_tags": ["Defensive Bash Scripting"], "tools_required": ["run_bash"]}],
                "cognition": {
                    "analysis": "Pillar 1 analysis of task requirements.",
                    "risks": "Pillar 2 risks of tool execution.",
                    "solution": "Pillar 3 solution decomposition.",
                    "verification": "Pillar 4 verification criteria.",
                },
            })
        elif role == "orchestrator":
            orchestrator_call_count[0] += 1
            domain_tag = "Defensive Bash Scripting" if orchestrator_call_count[0] > 1 else "NonExistentDomain"
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "annotated_plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "dag": {"nodes": ["t-001"], "edges": []},
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "task",
                        "domain_tags": [domain_tag],
                        "assigned_agent": "coder",
                        "tools_required": ["run_bash"],
                        "inputs": [],
                        "outputs": [],
                        "constraints": [],
                    }
                ],
                "cognition": {
                    "analysis": "Pillar 1 analysis of task DAG.",
                    "risks": "Pillar 2 risks of DAG scheduling.",
                    "solution": "Pillar 3 scheduling assignment.",
                    "verification": "Pillar 4 verification acceptance.",
                },
            })
        elif role == "reviewer":
            reviewer_called.append(True)
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "return_to": None,
                "violations": [],
                "cognition": {
                    "analysis": "Audit pass",
                    "risks": "No risks",
                    "solution": "Approve",
                    "verification": "Verified",
                },
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "fault_type": None,
                "threats": [],
                "cognition": {
                    "analysis": "STRIDE analysis pass",
                    "risks": "No threats",
                    "solution": "Clear",
                    "verification": "Verified",
                },
            })
        elif role == "coder":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "execution_result",
                "run_id": run_id,
                "task_id": "t-001",
                "role": "coder",
                "status": "success",
                "outputs": {},
                "cognition": {
                    "analysis": "Coder analysis of implementation.",
                    "risks": "No execution risks encountered.",
                    "solution": "Authored defensive script.",
                    "verification": "Syntax verified.",
                },
            })
        raise ValueError(f"Unexpected role: {role}")

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)

    final_state = run_pipeline(prompt=prompt, run_id=run_id, store=store)
    assert final_state["status"] == "complete"
    # Orchestrator was called twice: first iteration failed pre-filter, second iteration passed
    assert orchestrator_call_count[0] == 2
    assert len(reviewer_called) == 1


def test_raw_thinking_role_prompts():
    """Verify all canonical pipeline roles require <think> deliberation."""
    all_roles = [
        "architect",
        "orchestrator",
        "reviewer",
        "security",
        "coder",
        "sysadmin",
        "reviewer_code",
        "security_code",
    ]
    for r in all_roles:
        p = load_role_prompt(r)
        assert "<think>" in p, f"Role {r} prompt should require raw thinking"


def test_parse_llm_json_raw_thinking():
    """Verify parse_llm_json extracts <think> blocks and retains valid JSON."""
    from pipeline import parse_llm_json

    raw_response = (
        "<think>\n"
        "Deliberating on architecture: we need defensive bash standards.\n"
        "Checking domain tags: Defensive Bash Scripting.\n"
        "</think>\n"
        "```json\n"
        "{\n"
        '  "schema_version": "2.0",\n'
        '  "message_type": "plan",\n'
        '  "run_id": "run-test-01",\n'
        '  "tasks": []\n'
        "}\n"
        "```"
    )
    parsed = parse_llm_json(raw_response)
    assert parsed["schema_version"] == "2.0"
    assert parsed["message_type"] == "plan"
    assert "Deliberating on architecture" in parsed["cognition"]["chain_of_thought"]

    # Unclosed <think> fallback
    unclosed_response = (
        "<think>\n"
        "Analyzing risks without closing tag...\n"
        "```json\n"
        '{"schema_version": "2.0", "message_type": "plan"}\n'
        "```"
    )
    parsed_unclosed = parse_llm_json(unclosed_response)
    assert parsed_unclosed["schema_version"] == "2.0"
    assert "Analyzing risks" in parsed_unclosed["cognition"]["chain_of_thought"]


def test_pipeline_cli_tier_resolution(monkeypatch):
    """Verify pipeline main() CLI parser resolves tiers to corresponding winter-prime models."""
    from unittest.mock import patch
    from pipeline import main

    captured = {}

    def mock_run_pipeline(prompt, model, tier=None, **kwargs):
        captured["prompt"] = prompt
        captured["model"] = model
        captured["tier"] = tier
        return {"run_id": "test-run", "status": "complete"}

    with patch("pipeline.run_pipeline", side_effect=mock_run_pipeline):
        # 1. Default without flags -> winter-prime:latest
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt"])
        main()
        assert captured["model"] == "winter-prime:latest"
        assert captured["tier"] is None

        # 2. Tier 8gb -> winter-prime:8gb
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--tier", "8gb"])
        main()
        assert captured["model"] == "winter-prime:8gb"
        assert captured["tier"] == "8gb"

        # 3. Tier 16gb -> winter-prime:16gb
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--tier", "16gb"])
        main()
        assert captured["model"] == "winter-prime:16gb"
        assert captured["tier"] == "16gb"

        # 4. Tier 24gb -> winter-prime:24gb
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--tier", "24gb"])
        main()
        assert captured["model"] == "winter-prime:24gb"
        assert captured["tier"] == "24gb"

        # 5. Explicit model override with tier
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--tier", "8gb", "--model", "custom:model"])
        main()
        assert captured["model"] == "custom:model"
        assert captured["tier"] == "8gb"

    captured_dual = {}

    def mock_run_pipeline_dual(prompt, model, tier=None, auditor_model=None, dynamic_auditor=False, **kwargs):
        captured_dual["model"] = model
        captured_dual["auditor_model"] = auditor_model
        captured_dual["dynamic_auditor"] = dynamic_auditor
        return {"run_id": "test-run-dual", "status": "complete"}

    with patch("pipeline.run_pipeline", side_effect=mock_run_pipeline_dual):
        # 6. --dual-model flag sets builder to winter-prime:16gb and dynamic_auditor to True
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--dual-model"])
        main()
        assert captured_dual["model"] == "winter-prime:16gb"
        assert captured_dual["dynamic_auditor"] is True
        assert captured_dual["auditor_model"] is None

        # 7. --dual-model with custom explicit auditor
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--dual-model", "--auditor-model", "deepseek-r1:8b"])
        main()
        assert captured_dual["model"] == "winter-prime:16gb"
        assert captured_dual["auditor_model"] == "deepseek-r1:8b"
        assert captured_dual["dynamic_auditor"] is False

        # 8. --dynamic-auditor flag alone
        monkeypatch.setattr("sys.argv", ["pipeline.py", "test prompt", "--dynamic-auditor"])
        main()
        assert captured_dual["dynamic_auditor"] is True


def test_run_pipeline_dynamic_auditor_resolution(tmp_path, monkeypatch):
    """Verify run_pipeline with dynamic_auditor=True dynamically resolves auditor model."""
    runs_dir = tmp_path / "runs"
    store = ContextStore(runs_dir=str(runs_dir))

    prompt = "Review security configuration"
    run_id = "test-dynamic-auditor-001"
    models_received = {}

    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        models_received[role] = model
        if role == "architect":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "auditor_hint": "adversarial",
                "tasks": [{"task_id": "t-001", "description": "Audit system configuration and permissions", "domain_tags": ["Defensive Bash Scripting"], "tools_required": ["run_bash"]}],
                "cognition": {
                    "analysis": "Root cause analysis for system security and permissions configuration audit.",
                    "risks": "Potential permission denied errors and privilege escalation risks on audit.",
                    "solution": "Execute defensive bash checks with non-destructive inspections only.",
                    "verification": "Verify all assertions pass and review findings match expected baseline.",
                },
            })
        elif role == "orchestrator":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "annotated_plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "auditor_strategy": "adversarial",
                "dag": {"nodes": ["t-001"], "edges": []},
                "tasks": [{
                    "task_id": "t-001",
                    "description": "Audit system configuration and permissions",
                    "domain_tags": ["Defensive Bash Scripting"],
                    "assigned_agent": "sysadmin",
                    "tools_required": ["run_bash"],
                    "inputs": [],
                    "outputs": ["audit.log"],
                    "constraints": [],
                }],
                "cognition": {
                    "analysis": "Orchestrator analysis of DAG structure and security task assignment.",
                    "risks": "Potential scheduling conflicts or tool permission violations on execution.",
                    "solution": "Schedule single sysadmin audit task with adversarial secondary review.",
                    "verification": "Verify DAG acyclicity, schema conformity, and auditor selection.",
                },
            })
        elif role == "reviewer":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "return_to": None,
                "violations": [],
                "cognition": {
                    "analysis": "Reviewer audit confirms full architectural and prompt compliance.",
                    "risks": "No architectural deviations or missing safety boundaries detected.",
                    "solution": "Approve annotated plan for secondary security gate audit.",
                    "verification": "Confirmed prompt fidelity and deterministic validation pass.",
                },
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "fault_type": None,
                "threats": [],
                "cognition": {
                    "analysis": "STRIDE threat modeling completed across all trust boundaries.",
                    "risks": "No unmitigated privilege leaks or execution bypasses identified.",
                    "solution": "Clear audited plan for live agent dispatch and execution.",
                    "verification": "Sandbox containment and isolation parameters verified.",
                },
            })
        elif role == "sysadmin":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "execution_result",
                "run_id": run_id,
                "task_id": "t-001",
                "role": "sysadmin",
                "status": "success",
                "outputs": {},
                "cognition": {
                    "analysis": "Sysadmin execution analysis confirms clean inspection pass.",
                    "risks": "Zero environmental side effects or unwanted state changes observed.",
                    "solution": "Completed defensive audit task and generated structured output.",
                    "verification": "Verified exit code 0 and proper output file creation.",
                },
            })
        raise ValueError(f"Unexpected role: {role}")

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)

    final_state = run_pipeline(
        prompt=prompt,
        run_id=run_id,
        model="winter-prime:16gb",
        dynamic_auditor=True,
        store=store,
    )

    assert final_state["status"] == "complete"
    assert final_state["auditor_model"] == "deepseek-r1:8b"
    assert models_received["architect"] == "winter-prime:16gb"
    assert models_received["orchestrator"] == "winter-prime:16gb"
    assert models_received["reviewer"] == "deepseek-r1:8b"
    assert models_received["security"] == "deepseek-r1:8b"


def test_resume_pipeline_message_hydration(tmp_path, monkeypatch):
    """Verify that deserializing state.json with message paths hydrates dictionaries."""
    runs_dir = str(tmp_path / "runs")
    store = ContextStore(runs_dir=runs_dir)
    run_id = "run-test-resume-hydrate"

    plan = {
        "schema_version": "2.0",
        "message_type": "annotated_plan",
        "run_id": run_id,
        "tasks": [
            {
                "task_id": "t-001",
                "description": "Test task",
                "assigned_agent": "coder",
                "domain_tags": ["Python"],
            }
        ],
    }
    store.save_message(run_id, "annotated_plan", plan)
    store.save_message(run_id, "plan", {"run_id": run_id, "tasks": plan["tasks"]})
    store.save_message(run_id, "review_verdict", {"verdict": "approved"})
    store.save_message(run_id, "security_verdict", {"verdict": "cleared"})

    state = PipelineState(run_id=run_id, original_prompt="Test resume prompt")
    state.current_phase = "dispatch"
    state.messages = {
        "plan": f"runs/{run_id}/messages/plan.json",
        "annotated_plan": f"runs/{run_id}/messages/annotated_plan.json",
        "review_verdict": f"runs/{run_id}/messages/review_verdict.json",
        "security_verdict": f"runs/{run_id}/messages/security_verdict.json",
    }
    store.save_state(run_id, state.to_dict())

    # 1. from_dict with store hydrates messages
    state_dict = store.load(f"runs/{run_id}/state.json")
    restored = PipelineState.from_dict(state_dict, store=store)
    assert isinstance(restored.messages["annotated_plan"], dict)
    assert restored.messages["annotated_plan"]["tasks"][0]["task_id"] == "t-001"

    # 2. get_message works when unhydrated
    unhydrated = PipelineState.from_dict(state_dict)
    assert isinstance(unhydrated.messages["annotated_plan"], str)
    got = unhydrated.get_message("annotated_plan", store=store)
    assert isinstance(got, dict)
    assert got["tasks"][0]["task_id"] == "t-001"

    # 3. resume_pipeline completes without AttributeError
    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        if role == "coder":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "execution_result",
                "run_id": run_id,
                "task_id": "t-001",
                "role": "coder",
                "status": "success",
                "outputs": {
                    "test.sh": "#!/usr/bin/env bash\nset -euo pipefail\ntrap 'echo err' ERR\necho ok\n"
                },
                "cognition": {"analysis": "ok", "risks": "none", "solution": "done", "verification": "tested"},
            })
        elif role == "reviewer":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "violations": [],
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "threats": [],
            })
        return json.dumps({"status": "ok"})

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)
    monkeypatch.setattr("pipeline.validate_code_output", lambda *args, **kwargs: {"verdict": "approved", "violations": []})

    resumed_result = resume_pipeline(run_id=run_id, store=store)
    assert resumed_result["status"] == "complete"
    assert resumed_result["tasks"]["t-001"]["status"] == "success"

    import os
    if os.path.exists("test.sh"):
        os.remove("test.sh")




