"""Unit tests for mcp_cli.commands.pipeline — pure helpers and the revision loop (mocked)."""

import argparse

from mcp_core import transport
from mcp_cli.commands.pipeline import PipelineRunCommand

AUTHOR_OK = (
    "### 1. Analysis & Strategy\nWe will write a simple script.\n\n### 2. Implementation\n"
    "```bash\n#!/usr/bin/env bash\nset -euo pipefail\necho hello\n```"
)

AUTHOR_NO_CODE = "I'm sorry, I have no code to show you."

REVIEW_APPROVED = "All criteria satisfied.\nDECISION: APPROVED"
REVIEW_REVISION = "- Fix quoting issues\nDECISION: REVISION_REQUESTED"


def make_args(**overrides):
    defaults = {
        "file": "sysadmin/prompts/hello_world_test.md",
        "author": "qwen2.5-coder:7b",
        "reviewer": "qwen3:8b",
        "no_lint": False,
        "bootstrap": False,
        "max_retries": 2,
        "timeout": 300,
        "dry_run": False,
    }
    defaults.update(overrides)
    return argparse.Namespace(**defaults)


def scripted_call_mcp(monkeypatch, *, author=(AUTHOR_OK,), lint="No findings.", review=(REVIEW_APPROVED,)):
    """Monkeypatch transport.call_mcp with scripted per-tool responses."""
    calls = []
    author_q = list(author)
    review_q = list(review)

    def _fake(tool_name, arguments):
        calls.append((tool_name, arguments))
        if tool_name == "ollama_task_agent":
            return author_q.pop(0) if author_q else "DEFAULT"
        if tool_name == "shellcheck_inspect":
            return lint
        if tool_name == "ollama_chat":
            return review_q.pop(0) if review_q else "DEFAULT"
        return "DEFAULT"

    monkeypatch.setattr(transport, "call_mcp", _fake)
    return calls


# --- pure helper extraction ---

def test_extract_strategy():
    strategy = PipelineRunCommand._extract_strategy(AUTHOR_OK)
    assert strategy.startswith("### 1. Analysis & Strategy")
    assert "Implementation" not in strategy


def test_extract_stats():
    resp = "text\n*Generated by `qwen3:8b`: 123 tokens in 4.5s (27.3 t/s)*\nmore"
    assert PipelineRunCommand._extract_stats(resp) == "*Generated by `qwen3:8b`: 123 tokens in 4.5s (27.3 t/s)*"


def test_extract_stats_none_when_absent():
    assert PipelineRunCommand._extract_stats("no stats here") == ""


def test_extract_tool_calls_fenced_json():
    resp = (
        '```json\n{"name": "write_file", "arguments": {"path": "x.sh", '
        '"content": "echo hi", "make_executable": true}}\n```'
    )
    calls = PipelineRunCommand._extract_tool_calls(resp)
    # Both the fenced-block scanner and the raw-line scanner may surface the call.
    assert any(c.get("name") == "write_file" and c["arguments"].get("path") == "x.sh" for c in calls)


def test_extract_tool_calls_raw_line():
    resp = '{"name": "write_file", "arguments": {"path": "y.sh", "content": "echo y"}}'
    calls = PipelineRunCommand._extract_tool_calls(resp)
    assert any(c.get("name") == "write_file" for c in calls)


# --- revision loop orchestration ---

def test_revision_loop_approves_first_try(fake_send_terminal_mcp, monkeypatch):
    scripted_call_mcp(monkeypatch)
    result = PipelineRunCommand().revision_loop("Do something", make_args())
    assert result["approved"] is True
    assert result["iterations"] == 1
    assert "echo hello" in result["final_code_block"]


def test_revision_loop_revision_then_approve(fake_send_terminal_mcp, monkeypatch):
    scripted_call_mcp(monkeypatch, author=(AUTHOR_OK, AUTHOR_OK), review=(REVIEW_REVISION, REVIEW_APPROVED))
    result = PipelineRunCommand().revision_loop("Do something", make_args())
    assert result["approved"] is True
    assert result["iterations"] == 2


def test_revision_loop_exhausts_retries(fake_send_terminal_mcp, monkeypatch):
    scripted_call_mcp(monkeypatch, author=(AUTHOR_OK, AUTHOR_OK), review=(REVIEW_REVISION, REVIEW_REVISION))
    result = PipelineRunCommand().revision_loop("Do something", make_args(max_retries=2))
    assert result["approved"] is False
    assert result["iterations"] == 2


def test_revision_loop_format_error_retries(fake_send_terminal_mcp, monkeypatch):
    # First author response has no code block -> format error retry, then a valid one.
    scripted_call_mcp(monkeypatch, author=(AUTHOR_NO_CODE, AUTHOR_OK), review=(REVIEW_APPROVED,))
    result = PipelineRunCommand().revision_loop("Do something", make_args(max_retries=3))
    assert result["approved"] is True
    assert result["iterations"] == 2
