"""Unit tests for sysadmin.pipeline (Arc-Orc-Rev Pipeline Runner)."""

import json
import pytest

from mcp_core.context_store import ContextStore
from pipeline import (
    SMMP_PROFILES,
    PipelineState,
    parse_llm_json,
    load_role_prompt,
    run_pipeline,
    resume_pipeline,
)


def test_smmp_profiles():
    required_roles = ["architect", "orchestrator", "reviewer", "security", "coder", "sysadmin"]
    for role in required_roles:
        assert role in SMMP_PROFILES
        assert "temperature" in SMMP_PROFILES[role]
        assert "top_p" in SMMP_PROFILES[role]


def test_parse_llm_json():
    # 1. Plain JSON
    raw = '{"key": "value"}'
    assert parse_llm_json(raw) == {"key": "value"}

    # 2. Markdown fenced JSON
    fenced = "Here is your plan:\n```json\n{\n  \"action\": \"test\"\n}\n```"
    assert parse_llm_json(fenced) == {"action": "test"}

    # 3. JSON with Ollama telemetry footer
    with_telemetry = (
        '{"status": "ok"}\n\n---\n*Generated by `qwen2.5-coder:7b`: 50 tokens in 0.5s*'
    )
    assert parse_llm_json(with_telemetry) == {"status": "ok"}


def test_pipeline_state_serde():
    state = PipelineState("run-xyz", "Test prompt")
    state.add_event("test_event", "Detail message", "1")
    state.tasks["t-001"] = {"status": "pending", "retries": 0, "role": "coder"}

    d = state.to_dict()
    assert d["run_id"] == "run-xyz"
    assert d["status"] == "running"
    assert len(d["events"]) == 1

    restored = PipelineState.from_dict(d)
    assert restored.run_id == state.run_id
    assert restored.original_prompt == state.original_prompt
    assert restored.tasks == state.tasks


def test_load_role_prompt():
    prompt = load_role_prompt("architect")
    assert "Architect" in prompt
    assert "PlanMessage" in prompt


def test_run_pipeline_mocked_success(tmp_path, monkeypatch):
    runs_dir = tmp_path / "runs"
    store = ContextStore(runs_dir=str(runs_dir))

    prompt = "Deploy a defensive backup script"
    run_id = "test-run-mock-001"

    # Mock stage_chat responses
    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        if role == "architect":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "Write backup script",
                        "domain_tags": ["Defensive Bash Scripting"],
                        "tools_required": ["run_bash"],
                    }
                ],
                "cognition": {
                    "analysis": "Root cause analysis for backup deployment.",
                    "risks": "Potential permission denied on target volume.",
                    "solution": "Generate defensive script with explicit validation.",
                    "verification": "Verify exit code 0 and destination archive existence.",
                },
            })
        elif role == "orchestrator":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "annotated_plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "dag": {
                    "nodes": ["t-001"],
                    "edges": [],
                },
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "Write backup script",
                        "domain_tags": ["Defensive Bash Scripting"],
                        "assigned_agent": "coder",
                        "tools_required": ["run_bash"],
                        "inputs": [],
                        "outputs": ["backup.sh"],
                        "constraints": [],
                    }
                ],
                "cognition": {
                    "analysis": "Pillar 1 analysis of DAG structure and task assignments.",
                    "risks": "Pillar 2 risks of tool execution and concurrency.",
                    "solution": "Pillar 3 deterministic scheduling for single-task DAG.",
                    "verification": "Pillar 4 validation of DAG acyclicity and tool registry bindings.",
                },
            })
        elif role == "reviewer":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "return_to": None,
                "violations": [],
                "cognition": {
                    "analysis": "Plan meets all architectural and safety requirements.",
                    "risks": "No blocking risks identified during audit.",
                    "solution": "Approve plan for STRIDE threat modeling.",
                    "verification": "Confirmed prompt fidelity and schema compliance.",
                },
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "fault_type": None,
                "threats": [],
                "cognition": {
                    "analysis": "STRIDE evaluation performed across all categories.",
                    "risks": "No unmitigated threats detected.",
                    "solution": "Clear plan for dispatch.",
                    "verification": "Verified sandbox constraints and tool boundaries.",
                },
            })
        raise ValueError(f"Unexpected role: {role}")

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)

    final_state = run_pipeline(prompt=prompt, run_id=run_id, store=store)

    assert final_state["status"] == "complete"
    assert final_state["current_phase"] == "complete"
    assert "t-001" in final_state["tasks"]

    # Verify run was sealed to cold storage
    archive_path = store._archive_path(run_id)
    assert (tmp_path / "runs" / f"{run_id}.tar.zst").exists()

    # Verify we can load back state from sealed archive
    loaded_state = store.load(f"runs/{run_id}/state.json")
    assert loaded_state["status"] == "complete"


def test_run_pipeline_pre_filter_rejection_routes_to_orchestrator(tmp_path, monkeypatch):
    runs_dir = tmp_path / "runs"
    store = ContextStore(runs_dir=str(runs_dir))

    prompt = "Test pre-filter routing"
    run_id = "test-run-mock-002"
    reviewer_called = []
    orchestrator_call_count = [0]

    def fake_stage_chat(role, system_prompt, user_content, model="winter-prime:latest", tools=None):
        if role == "architect":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "tasks": [{"task_id": "t-001", "description": "task", "domain_tags": ["Defensive Bash Scripting"], "tools_required": ["run_bash"]}],
                "cognition": {
                    "analysis": "Pillar 1 analysis of task requirements.",
                    "risks": "Pillar 2 risks of tool execution.",
                    "solution": "Pillar 3 solution decomposition.",
                    "verification": "Pillar 4 verification criteria.",
                },
            })
        elif role == "orchestrator":
            orchestrator_call_count[0] += 1
            domain_tag = "Defensive Bash Scripting" if orchestrator_call_count[0] > 1 else "NonExistentDomain"
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "annotated_plan",
                "run_id": run_id,
                "original_prompt": prompt,
                "dag": {"nodes": ["t-001"], "edges": []},
                "tasks": [
                    {
                        "task_id": "t-001",
                        "description": "task",
                        "domain_tags": [domain_tag],
                        "assigned_agent": "coder",
                        "tools_required": ["run_bash"],
                        "inputs": [],
                        "outputs": [],
                        "constraints": [],
                    }
                ],
                "cognition": {
                    "analysis": "Pillar 1 analysis of task DAG.",
                    "risks": "Pillar 2 risks of DAG scheduling.",
                    "solution": "Pillar 3 scheduling assignment.",
                    "verification": "Pillar 4 verification acceptance.",
                },
            })
        elif role == "reviewer":
            reviewer_called.append(True)
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "review_verdict",
                "run_id": run_id,
                "verdict": "approved",
                "return_to": None,
                "violations": [],
                "cognition": {
                    "analysis": "Audit pass",
                    "risks": "No risks",
                    "solution": "Approve",
                    "verification": "Verified",
                },
            })
        elif role == "security":
            return json.dumps({
                "schema_version": "2.0",
                "message_type": "security_verdict",
                "run_id": run_id,
                "verdict": "cleared",
                "fault_type": None,
                "threats": [],
                "cognition": {
                    "analysis": "STRIDE analysis pass",
                    "risks": "No threats",
                    "solution": "Clear",
                    "verification": "Verified",
                },
            })
        raise ValueError(f"Unexpected role: {role}")

    monkeypatch.setattr("pipeline.stage_chat", fake_stage_chat)

    final_state = run_pipeline(prompt=prompt, run_id=run_id, store=store)
    assert final_state["status"] == "complete"
    # Orchestrator was called twice: first iteration failed pre-filter, second iteration passed
    assert orchestrator_call_count[0] == 2
    assert len(reviewer_called) == 1
