#!/usr/bin/env python3
"""
Local Ollama MCP Server
Provides a Model Context Protocol (MCP) interface over stdio to delegate tasks,
chat, code generation, and model management to a local Ollama instance.
"""

import json
import os
import sys
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434").rstrip("/")
PROTOCOL_VERSION = "2024-11-05"


def _http_request(endpoint: str, method: str = "GET", data: Optional[Dict[str, Any]] = None, timeout: int = 120) -> Dict[str, Any]:
    url = f"{OLLAMA_HOST}{endpoint}"
    req = urllib.request.Request(url, method=method)
    req.add_header("Content-Type", "application/json")
    
    body = json.dumps(data).encode("utf-8") if data is not None else None
    try:
        with urllib.request.urlopen(req, data=body, timeout=timeout) as response:
            res_body = response.read().decode("utf-8")
            if not res_body.strip():
                return {}
            # Handle streaming responses vs single json
            if "\n" in res_body.strip() and not res_body.strip().startswith("{"):
                # Multi-line JSON lines (NDJSON)
                lines = [json.loads(line) for line in res_body.strip().splitlines() if line.strip()]
                return {"lines": lines}
            return json.loads(res_body)
    except urllib.error.URLError as e:
        raise RuntimeError(f"Failed to connect to Ollama at {url}: {e}")
    except Exception as e:
        raise RuntimeError(f"Ollama API request error ({url}): {e}")


def handle_list_models() -> str:
    """Lists all models installed in the local Ollama instance."""
    data = _http_request("/api/tags", method="GET")
    models = data.get("models", [])
    if not models:
        return "No models installed in local Ollama."
    
    result = ["Installed Ollama Models:"]
    for m in models:
        name = m.get("name", "unknown")
        size_gb = m.get("size", 0) / (1024 ** 3)
        details = m.get("details", {})
        family = details.get("family", "")
        quant = details.get("quantization_level", "")
        param_size = details.get("parameter_size", "")
        result.append(f"- **{name}** ({size_gb:.2f} GB) | Params: {param_size} | Family: {family} | Quant: {quant}")
    
    return "\n".join(result)


def handle_chat(
    model: str,
    prompt: Optional[str] = None,
    messages: Optional[List[Dict[str, str]]] = None,
    system_prompt: Optional[str] = None,
    temperature: float = 0.7,
    num_ctx: int = 4096
) -> str:
    """Sends a chat request to local Ollama."""
    chat_messages = []
    if system_prompt:
        chat_messages.append({"role": "system", "content": system_prompt})
    
    if messages:
        chat_messages.extend(messages)
    elif prompt:
        chat_messages.append({"role": "user", "content": prompt})
    else:
        raise ValueError("Either 'prompt' or 'messages' must be provided.")
    
    payload = {
        "model": model,
        "messages": chat_messages,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx
        }
    }
    
    response = _http_request("/api/chat", method="POST", data=payload, timeout=300)
    message = response.get("message", {})
    content = message.get("content", "")
    
    # Extract performance metrics if available
    eval_count = response.get("eval_count", 0)
    eval_duration = response.get("eval_duration", 0)
    tps = (eval_count / (eval_duration / 1e9)) if eval_duration > 0 else 0
    
    stats = f"\n\n---\n*Generated by `{model}`: {eval_count} tokens in {eval_duration/1e9:.2f}s ({tps:.1f} t/s)*"
    return content + stats


def handle_task_agent(
    task: str,
    model: str = "qwen3:8b",
    context: Optional[str] = None,
    task_type: str = "general",
    num_ctx: int = 4096
) -> str:
    """
    Executes a structured task delegation pass to a local Ollama model.
    Encourages structured step-by-step reasoning, execution, and self-verification.
    """
    system_prompt = (
        "You are an expert local AI agent and systems engineer. "
        "When given a task, follow this structured format:\n"
        "1. **Analysis & Strategy**: Deconstruct the problem and requirements.\n"
        "2. **Implementation / Solution**: Provide clean, idiomatic, and robust code, configurations, or commands.\n"
        "3. **Verification & Testing**: Explain how to test and verify the solution (idempotency, dry-run, syntax checks).\n"
        "4. **Risks & Edge Cases**: Detail any caveats or failure modes."
    )
    
    user_prompt = f"### Task Request ({task_type}):\n{task}"
    if context:
        user_prompt += f"\n\n### Workspace Context:\n{context}"
        
    return handle_chat(
        model=model,
        prompt=user_prompt,
        system_prompt=system_prompt,
        temperature=0.2,
        num_ctx=num_ctx
    )


def handle_pull_model(model: str) -> str:
    """Triggers pulling a model into Ollama."""
    payload = {"name": model, "stream": False}
    _http_request("/api/pull", method="POST", data=payload, timeout=600)
    return f"Successfully pulled model `{model}` into local Ollama."


# MCP Tool Definitions
TOOLS = [
    {
        "name": "ollama_list_models",
        "description": "Lists all AI models currently installed in the local Ollama instance with their sizes, parameter counts, and quantization levels.",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "ollama_chat",
        "description": "Send a prompt or chat messages to a local Ollama model (e.g. qwen3:8b, mistral-nemo:12b, qwen2.5-coder:7b) and receive the generated response.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": "The name of the local Ollama model to use (e.g., 'qwen3:8b', 'mistral-nemo:12b', 'qwen2.5-coder:7b')."
                },
                "prompt": {
                    "type": "string",
                    "description": "The user prompt to generate a response for."
                },
                "system_prompt": {
                    "type": "string",
                    "description": "Optional system prompt defining the persona or task constraints."
                },
                "temperature": {
                    "type": "number",
                    "description": "Sampling temperature (default: 0.7)."
                },
                "num_ctx": {
                    "type": "integer",
                    "description": "Context window size in tokens (default: 4096)."
                }
            },
            "required": ["model", "prompt"]
        }
    },
    {
        "name": "ollama_task_agent",
        "description": "Delegate a complex coding, sysadmin, or reasoning task to a local Ollama model with structured analysis, implementation, and verification output.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "task": {
                    "type": "string",
                    "description": "The task description or goal to solve."
                },
                "model": {
                    "type": "string",
                    "description": "Local model to use (defaults to 'qwen3:8b')."
                },
                "context": {
                    "type": "string",
                    "description": "Optional workspace context, file contents, or diagnostic logs."
                },
                "task_type": {
                    "type": "string",
                    "description": "Category of the task: 'sysadmin', 'ansible', 'coding', 'reasoning', or 'general'."
                },
                "num_ctx": {
                    "type": "integer",
                    "description": "Context length in tokens (default: 4096)."
                }
            },
            "required": ["task"]
        }
    },
    {
        "name": "ollama_pull_model",
        "description": "Download and pull a new model from the Ollama library into the local instance.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string",
                    "description": "The name/tag of the model to pull (e.g., 'qwen2.5-coder:7b', 'olmoe:7b-instruct')."
                }
            },
            "required": ["model"]
        }
    }
]


def process_jsonrpc(request: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Processes an incoming JSON-RPC 2.0 request."""
    method = request.get("method")
    req_id = request.get("id")
    params = request.get("params", {})
    
    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {
                    "tools": {}
                },
                "serverInfo": {
                    "name": "local-ollama-mcp",
                    "version": "1.0.0"
                }
            }
        }
    
    if method == "notifications/initialized":
        return None  # Notifications do not return responses
    
    if method == "ping":
        return {"jsonrpc": "2.0", "id": req_id, "result": {}}
    
    if method == "tools/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "tools": TOOLS
            }
        }
    
    if method == "tools/call":
        tool_name = params.get("name")
        args = params.get("arguments", {})
        
        try:
            if tool_name == "ollama_list_models":
                text = handle_list_models()
            elif tool_name == "ollama_chat":
                text = handle_chat(
                    model=args.get("model", "qwen3:8b"),
                    prompt=args.get("prompt"),
                    system_prompt=args.get("system_prompt"),
                    temperature=float(args.get("temperature", 0.7)),
                    num_ctx=int(args.get("num_ctx", 4096))
                )
            elif tool_name == "ollama_task_agent":
                text = handle_task_agent(
                    task=args.get("task", ""),
                    model=args.get("model", "qwen3:8b"),
                    context=args.get("context"),
                    task_type=args.get("task_type", "general"),
                    num_ctx=int(args.get("num_ctx", 4096))
                )
            elif tool_name == "ollama_pull_model":
                text = handle_pull_model(args.get("model", ""))
            else:
                return {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "isError": True,
                        "content": [{"type": "text", "text": f"Unknown tool: {tool_name}"}]
                    }
                }
                
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [{"type": "text", "text": text}]
                }
            }
        except Exception as e:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "isError": True,
                    "content": [{"type": "text", "text": f"Error executing {tool_name}: {str(e)}"}]
                }
            }
    
    # Method not found
    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "error": {
            "code": -32601,
            "message": f"Method not found: {method}"
        }
    }


def main():
    """Main stdio loop for MCP server."""
    # Ensure stdout/stderr encoding
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
            response = process_jsonrpc(request)
            if response is not None:
                sys.stdout.write(json.dumps(response) + "\n")
                sys.stdout.flush()
        except json.JSONDecodeError:
            err_response = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32700, "message": "Parse error"}
            }
            sys.stdout.write(json.dumps(err_response) + "\n")
            sys.stdout.flush()
        except Exception as e:
            sys.stderr.write(f"Unexpected error in MCP loop: {e}\n")
            sys.stderr.flush()


if __name__ == "__main__":
    main()
